version: '3'

services:
  backend:
    image: elhadjaoui/backend:latest
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules    
    
  frontend:
    image: elhadjaoui/frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
   
